
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CenterServerManagementService", targetNamespace = "http://Server/", wsdlLocation = "http://localhost:8080/Comp6231WebService/services/CenterServerManagement?wsdl")
public class CenterServerManagementService
    extends Service
{

    private final static URL CENTERSERVERMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CENTERSERVERMANAGEMENTSERVICE_EXCEPTION;
    private final static QName CENTERSERVERMANAGEMENTSERVICE_QNAME = new QName("http://Server/", "CenterServerManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Comp6231WebService/services/CenterServerManagement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CENTERSERVERMANAGEMENTSERVICE_WSDL_LOCATION = url;
        CENTERSERVERMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public CenterServerManagementService() {
        super(__getWsdlLocation(), CENTERSERVERMANAGEMENTSERVICE_QNAME);
    }

    public CenterServerManagementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CENTERSERVERMANAGEMENTSERVICE_QNAME, features);
    }

    public CenterServerManagementService(URL wsdlLocation) {
        super(wsdlLocation, CENTERSERVERMANAGEMENTSERVICE_QNAME);
    }

    public CenterServerManagementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CENTERSERVERMANAGEMENTSERVICE_QNAME, features);
    }

    public CenterServerManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CenterServerManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DSMSWebIntrfc
     */
    @WebEndpoint(name = "CenterServerManagementPort")
    public DSMSWebIntrfc getCenterServerManagementPort() {
        return super.getPort(new QName("http://Server/", "CenterServerManagementPort"), DSMSWebIntrfc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DSMSWebIntrfc
     */
    @WebEndpoint(name = "CenterServerManagementPort")
    public DSMSWebIntrfc getCenterServerManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Server/", "CenterServerManagementPort"), DSMSWebIntrfc.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CENTERSERVERMANAGEMENTSERVICE_EXCEPTION!= null) {
            throw CENTERSERVERMANAGEMENTSERVICE_EXCEPTION;
        }
        return CENTERSERVERMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
