
package server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DSMSWebIntrfc", targetNamespace = "http://Server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DSMSWebIntrfc {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTRecord", targetNamespace = "http://Server/", className = "server.CreateTRecord")
    @ResponseWrapper(localName = "createTRecordResponse", targetNamespace = "http://Server/", className = "server.CreateTRecordResponse")
    @Action(input = "http://Server/DSMSWebIntrfc/createTRecordRequest", output = "http://Server/DSMSWebIntrfc/createTRecordResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://Server/DSMSWebIntrfc/createTRecord/Fault/IOException")
    })
    public String createTRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSRecord", targetNamespace = "http://Server/", className = "server.CreateSRecord")
    @ResponseWrapper(localName = "createSRecordResponse", targetNamespace = "http://Server/", className = "server.CreateSRecordResponse")
    @Action(input = "http://Server/DSMSWebIntrfc/createSRecordRequest", output = "http://Server/DSMSWebIntrfc/createSRecordResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://Server/DSMSWebIntrfc/createSRecord/Fault/IOException")
    })
    public String createSRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecordCounts", targetNamespace = "http://Server/", className = "server.GetRecordCounts")
    @ResponseWrapper(localName = "getRecordCountsResponse", targetNamespace = "http://Server/", className = "server.GetRecordCountsResponse")
    @Action(input = "http://Server/DSMSWebIntrfc/getRecordCountsRequest", output = "http://Server/DSMSWebIntrfc/getRecordCountsResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://Server/DSMSWebIntrfc/getRecordCounts/Fault/IOException")
    })
    public String getRecordCounts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editRecord", targetNamespace = "http://Server/", className = "server.EditRecord")
    @ResponseWrapper(localName = "editRecordResponse", targetNamespace = "http://Server/", className = "server.EditRecordResponse")
    @Action(input = "http://Server/DSMSWebIntrfc/editRecordRequest", output = "http://Server/DSMSWebIntrfc/editRecordResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://Server/DSMSWebIntrfc/editRecord/Fault/IOException")
    })
    public String editRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferRecord", targetNamespace = "http://Server/", className = "server.TransferRecord")
    @ResponseWrapper(localName = "transferRecordResponse", targetNamespace = "http://Server/", className = "server.TransferRecordResponse")
    @Action(input = "http://Server/DSMSWebIntrfc/transferRecordRequest", output = "http://Server/DSMSWebIntrfc/transferRecordResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://Server/DSMSWebIntrfc/transferRecord/Fault/IOException")
    })
    public String transferRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws IOException_Exception
    ;

}
